# Generated by Django 4.0.4 on 2022-11-23 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0051_pancin_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='gst_lutbond',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
    ]
