# Generated by Django 4.0.4 on 2022-11-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_gst_lutbond_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst_lutbond',
            name='validity_from',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gst_lutbond',
            name='validity_to',
            field=models.CharField(max_length=50),
        ),
    ]
