# Generated by Django 4.0.4 on 2022-11-30 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_alter_gst_lutbond_validity_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='under',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='app1.createstockgrp'),
        ),
    ]
