# Generated by Django 4.0.4 on 2022-11-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_alter_stock_itemcreation_under'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=225)),
                ('particular', models.CharField(max_length=225)),
                ('voucher_type', models.CharField(max_length=225)),
                ('voucher_number', models.CharField(max_length=225)),
                ('quntity', models.CharField(default=0, max_length=225)),
                ('value', models.CharField(default=0, max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='add_voucher2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default='Null', max_length=225)),
                ('particular', models.CharField(blank=True, default='Null', max_length=225)),
                ('voucher_type', models.CharField(blank=True, default='Null', max_length=225)),
                ('voucher_number', models.CharField(blank=True, default='Null', max_length=225)),
                ('debit', models.CharField(blank=True, default=0, max_length=225)),
                ('credit', models.CharField(blank=True, default=0, max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='add_voucher3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default='Null', max_length=225)),
                ('particular', models.CharField(blank=True, default='Null', max_length=225)),
                ('voucher_type', models.CharField(blank=True, default='Null', max_length=225)),
                ('voucher_number', models.CharField(blank=True, default='Null', max_length=225)),
                ('debit', models.CharField(blank=True, default=0, max_length=225)),
                ('credit', models.CharField(blank=True, default=0, max_length=225)),
            ],
        ),
    ]
