# Generated by Django 4.0.4 on 2022-11-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0056_alter_stock_itemcreation_under'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally_ledger',
            name='credit_period',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
